Feature: The program can sort tagged files into groups
  Description: When files are tagged then they can be sorted and/or given an order. This is meant to assist users
  in creating new groups from other groups

#    Background:
#      Given there are files to test
#      And there is a fresh tmsu database with files
#      And there are files with tags
#
#    Scenario:
#      When when the user opens the sort window
#      Then the user can choose a number of tags tag
#
#    Scenario:
#      When the user chooses any number of tags
#      Then they can sort a list of files that are tagged
#
#    Scenario:
#      When the user sorts a list
#      Then they can save the ordered list as a file
#
#    Scenario:
#      When the user chooses any number of tags
#      Then they can apply a new tag to the group
